s3:
  bucket: s3-bucket-name
  prefix: prefix/inside/bucket
  multipart_threshold: 104857600 # 100MB - files >= this size use multipart upload (optional, default: 100MB)
  multipart_part_size: 10485760  # 10MB - size of each upload part (optional, default: 10MB)
  multipart_concurrency: 10      # concurrent part uploads (optional, default: 10)

  # backups will be stored in s3://s3-bucket-name/prefix/inside/bucket/[service name]/[path name]/
services:
  service-example:
    paths:
      data: /path/to/service_data
      config: /path/to/service_config
    include_folders:
      data:
        - folders in /path/to/service_data
        - you want
        - to include in the archive
      # since 'config' doesnt have an `include_folders`
      # it will backup everything in /path/to/service_config
retention: 14 # days
auto_cleanup: true # automatically clean up old backups after each backup operation

notifications:
  discord_webhook: 'discord webhook url'
  on_success: true
  on_error: true
  on_warning: true

backup:
  temp_dir: /tmp/stash-backups
  preserve_acls: true
  compression: true
  min_size: 1024 # bytes - minimum backup archive size for validation (not source directory size)